version: 2.1

executors:
  node:
    working_directory: ~/some-dir
    docker:
      - image: circleci/node:12.0-browsers

commands:
  say-hi:
    description: Greeting is important
    steps:
      - run: echo "What's up duck?"
  print-some-var:
    steps:
      - run: echo $SOME_VAR
  set-some-var:
    parameters:
      value:
        type: string
        default: "false"
    steps:
      - run: SOME_VAR="<< parameters.value >>"
  check-version-tag:
    steps:
      - run:
          command: |
            IS_VALID_SEMVER="^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$"
            if [[ $(git tag --contains HEAD) =~ $(echo $IS_VALID_SEMVER) ]]; then
                echo "proper version tag"
            else
                echo "nope"
            fi

jobs:
  some-job:
    executor: node
    steps:
      - checkout
      - check-version-tag

workflows:
  some-workflow:
    jobs:
      - some-job
