version: 2.1

executors:
  node-executor:
    working_directory: ~/some-dir
    docker:
      - image: circleci/node:12.0-browsers

commands:
  print-tags:
    steps:
      - run: git tag -l
  check-version-tag:
    steps:
      - run:
          command: |
            IS_VALID_SEMVER="^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$"
            if [[ $(git tag --contains HEAD) =~ $(echo $IS_VALID_SEMVER) ]]; then
                echo "proper version tag"
            else
                echo "nope"
            fi
  version-bump:
    parameters:
      semver:
        type: enum
        enum: ["major", "minor", "patch"]
      protocol:
        type: string
        default: https://
      push-url:
        type: string
        default: github.com/yucho/circleci-playground.git
    steps:
      - run:
          command: |
            IS_VALID_SEMVER="^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$"
            if [[ $(git tag --contains HEAD) =~ $(echo $IS_VALID_SEMVER) ]]; then
              echo "Version update error: version tag already exists"
            else
              git config credential.helper 'cache --timeout=120'
              git config user.email "$GIT_USER_EMAIL"
              git config user.name "$GIT_USER_NAME"
              npm version << parameters.semver >>

              # Push quietly to prevent displaying token in shell
              git push -q << parameters.protocol >>${GITHUB_PERSONAL_TOKEN}@<< parameters.push-url >> master --tags
            fi

jobs:
  filter-master:
    executor: node-executor
    steps:
      - checkout
      - run:
          command: |
            # Due to limitation of Circle CI tags filters, we need this job to filter out versioned commit
            IS_VALID_SEMVER="^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$"
            if [[ $(git tag --contains HEAD) =~ $(echo $IS_VALID_SEMVER) ]]; then
              # Error out to prevent downstream jobs from running
                exit 1
            else
                exit 1
            fi

  npm-version-bump:
    executor: node-executor
    steps:
      - checkout
      - print-tags
      - check-version-tag

  patch-version-bump:
    executor: node-executor
    steps:
      - checkout
      - version-bump:
          semver: patch
          push-url: github.com/yucho/circleci-playground.git
  minor-version-bump:
    executor: node-executor
    steps:
      - checkout
      - version-bump:
          semver: minor
          push-url: github.com/yucho/circleci-playground.git
  major-version-bump:
    executor: node-executor
    steps:
      - checkout
      - version-bump:
          semver: major
          push-url: github.com/yucho/circleci-playground.git

workflows:
  versioning:
    jobs:
      - filter-master:
          filters:
            branches:
              only: master
      - patch-version-bump:
          context: yucho-open-source
          type: approval
          requires:
            - filter-master
      - minor-version-bump:
          context: yucho-open-source
          type: approval
          requires:
            - filter-master
      - major-version-bump:
          context: yucho-open-source
          type: approval
          requires:
            - filter-master

  i-should-not-run-after-approval:
    jobs:
      - git-version-update:
          type: approval
          context: yucho-open-source
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$/
