version: 2.1

executors:
  node-executor:
    working_directory: ~/some-dir
    docker:
      - image: circleci/node:12.0-browsers

commands:
  print-tags:
    steps:
      - run: git tag -l
  check-version-tag:
    steps:
      - run:
          command: |
            IS_VALID_SEMVER="^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$"
            if [[ $(git tag --contains HEAD) =~ $(echo $IS_VALID_SEMVER) ]]; then
                echo "proper version tag"
            else
                echo "nope"
            fi
  version-update:
    parameters:
      semver:
        type: enum
        enum: ["major", "minor", "patch"]
      protocol:
        type: string
        default: https://
      push-url:
        type: string
        default: github.com/yucho/circleci-playground.git
    steps:
      - run:
          command: |
            # git config credential.helper 'cache --timeout=120'
            # git config user.email "$GIT_USER_EMAIL"
            # git config user.name "$GIT_USER_NAME"
            # npm version << parameters.semver >>

            # Push quietly to prevent displaying token in shell
            # git push -q << parameters.protocol >>${GITHUB_PERSONAL_TOKEN}@<< parameters.push-url >> master --tags

            git tag
            git tag --contains HEAD

jobs:
  checkout-master:
    executor: node-executor
    steps:
      - checkout
  npm-version-bump:
    executor: node-executor
    steps:
      - checkout
      - print-tags
      - check-version-tag

  git-version-update:
    executor: node-executor
    steps:
      - checkout
      - version-update:
          semver: patch
          push-url: github.com/yucho/circleci-playground.git

workflows:
  versioning:
    jobs:
      - git-version-update:
          context: yucho-open-source
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$/
  i-should-run:
    jobs:
      - git-version-update:
          context: yucho-open-source
          filters:
            branches:
              ignore: /.*/
            tags:
              only: v2.2.5
  i-should-not-run:
    jobs:
      - git-version-update:
          context: yucho-open-source
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: v2.2.5
  i-should-not-run-after-approval:
    jobs:
      - git-version-update:
          type: approval
          context: yucho-open-source
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$/
