version: 2.1

executors:
  node-executor:
    working_directory: ~/some-dir
    docker:
      - image: circleci/node:12.0-browsers

commands:
  print-tags:
    steps:
      - run: git tag -l
  check-version-tag:
    steps:
      - run:
          command: |
            IS_VALID_SEMVER="^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$"
            if [[ $(git tag --contains HEAD) =~ $(echo $IS_VALID_SEMVER) ]]; then
                echo "proper version tag"
            else
                echo "nope"
            fi
  version-update:
    parameters:
      semver:
        type: enum
        enum: ["major", "minor", "patch"]
    steps:
      - run:
          command: |
            pwd
            npm version << parameters.semver >>
            git push

jobs:
  npm-version-bump:
    executor: node-executor
    steps:
      - checkout
      - print-tags
      - check-version-tag

  git-version-update:
    executor: node-executor
    steps:
      - checkout
      - version-update:
          semver: patch

workflows:
  versioning:
    jobs:
      - git-version-update:
          filters:
            tags:
              ignore: /^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$/
