version: 2.1

executors:
  node:
    working_directory: ~/some-dir
    docker:
      - image: circleci/node:12.0-browsers

commands:
  say-hi:
    description: Greeting is important
    steps:
      - run: echo "What's up duck?"


jobs:
  some-job:
    executor: node
    steps:
      - say-hi

workflows:
  some-workflow:
    jobs:
      - some-job
