version: 2.1

executors:
  node-executor:
    working_directory: ~/some-dir
    docker:
      - image: circleci/node:12.0-browsers

commands:
  version-bump:
    parameters:
      semver:
        type: enum
        enum: ["major", "minor", "patch"]
      protocol:
        type: string
        default: https://
      push-url:
        type: string
        default: github.com/yucho/circleci-playground.git
    steps:
      - run:
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "$GIT_USER_EMAIL"
            git config user.name "$GIT_USER_NAME"
            npm version << parameters.semver >>

            # Push quietly to prevent displaying token in shell
            git push -q << parameters.protocol >>${GITHUB_PERSONAL_TOKEN}@<< parameters.push-url >> master --tags

jobs:
  filter-master:
    executor: node-executor
    steps:
      - checkout
      - run:
          command: |
            # Due to limitation of Circle CI tags filters, we need this job to filter out versioned commit
            IS_VALID_SEMVER="^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$"
            if [[ $(git tag --contains HEAD) =~ $(echo $IS_VALID_SEMVER) ]]; then
              # Error out to prevent downstream jobs from running
                exit 1
            fi

  run-patch-version-bump:
    executor: node-executor
    steps:
      - checkout
      - version-bump:
          semver: patch

  run-minor-version-bump:
    executor: node-executor
    steps:
      - checkout
      - version-bump:
          semver: minor

  run-major-version-bump:
    executor: node-executor
    steps:
      - checkout
      - version-bump:
          semver: major

  run-deploy:
    executor: node-executor
    steps:
      - run:
          command: echo "Put deploy code here"

workflows:
  versioning:
    jobs:
      - filter-master:
          filters:
            branches:
              only: master
      - patch-version-bump:
          type: approval
          requires:
            - filter-master
      - run-patch-version-bump:
          context: yucho-open-source
          requires:
            - patch-version-bump
      - minor-version-bump:
          type: approval
          requires:
            - filter-master
      - run-minor-version-bump:
          context: yucho-open-source
          requires:
            - minor-version-bump
      - major-version-bump:
          type: approval
          requires:
            - filter-master
      - run-major-version-bump:
          context: yucho-open-source
          requires:
            - major-version-bump

  deploy:
    jobs:
      - deploy:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?((([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$/
      - run-deploy:
          context: yucho-open-source
          requires:
            - deploy
