version: 2.1

executors:
  node:
    working_directory: ~/some-dir
    docker:
      - image: circleci/node:12.0-browsers

commands:
  say-hi:
    description: Greeting is important
    steps:
      - run: echo "What's up duck?"
  print-some-var:
    steps:
      - run: echo $SOME_VAR
  set-some-var:
    parameters:
      value:
        type: string
        default: "false"
    steps:
      - run: SOME_VAR="<< parameters.value >>"


jobs:
  some-job:
    executor: node
    steps:
      - say-hi
      - print-some-var
      - set-some-var:
          value: I am your father
      - print-some-var
      - set-some-var:
          value: "true"
      - print-some-var

workflows:
  some-workflow:
    jobs:
      - some-job
